In [35]:
import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt


# function that gives input
def theta_func(t):
    t0 = 40
    nu = 0.00
    theta0 = np.exp(9.495)
    value = theta0 * np.exp(-nu * (t - t0))
    return value

# function that gives chimerism in source
def chi_T1(t):
    chiEst = 0.88
    qEst = 0.01
    if ((t - 15)>0):
        value = chiEst * (1 - np.exp(-qEst * (t-15)))
    else:
        value = 0.0
    return value

# function that describes changes in source chimerism
def eps_donor(t):
    eps_0 = 0.068;  eps_f  = 0.01;  A = 115;
    k_val = np.exp(- eps_f * (t + A)) + eps_0
    return k_val

timeseq = np.linspace(40, 100, num=20)
print(chi_T1(16))

0.008756146300732065


In [36]:

# function that returns dy/dt
def model(y,t,tb, psi,r,b,k):
    y1, y2, y3, y4 = y 
    eps_host=0.068
    eps_donor=0.9
    
    dy1dt = (psi * theta_func(t) * chi_T1(t-tb) * eps_donor) + r * (2 * y2 + y1) - (b + (k + r)) * y1
    dy2dt = (psi * theta_func(t) * chi_T1(t-tb) * (1-eps_donor)) + b * y1 - (r + (k + r)) * y2
    
    dy3dt = (psi * theta_func(t) * (1-chi_T1(t-tb)) * eps_host) + r * (2 * y4 + y3) - (b + (k + r)) * y3
    dy4dt = (psi * theta_func(t) * (1-chi_T1(t-tb)) * (1-eps_host)) + b * y3 - (r + (k + r)) * y4
    dydt = (dy1dt, dy2dt, dy3dt, dy4dt)
    return dydt

# initial condition
y0 = (0, 0, 4000, 1000)

# time points
t = np.linspace(40, 300, num=20)

# solve ODE
tb=45
k=0.05
psi = 0.3
r=0.005
b=0.25
y = odeint(model,y0,t, args=(tb,psi,r,b,k,))
print(y)


[[    0.             0.          4000.          1000.        ]
 [    0.             0.          2046.33926052 39997.40265541]
 [  455.63524357   369.08241625  2670.28704919 57236.87354353]
 [ 1789.91202265  3443.08498274  2822.71933568 62104.10902708]
 [ 3066.58958025  8222.21102152  2736.94185663 60890.37239683]
 [ 4223.29955608 13462.39457018  2551.9723605  57077.94100436]
 [ 5253.72729797 18573.54497572  2335.08596324 52363.76546117]
 [ 6163.29174263 23304.02393829  2117.90169453 47551.59756081]
 [ 6962.03918929 27567.23949812  1914.34978704 43001.27315315]
 [ 7661.41243814 31354.7055264   1729.69516904 38854.5145101 ]
 [ 8272.74351764 34692.83741653  1565.05669917 35148.10059474]
 [ 8806.59757469 37621.73235321  1419.65817161 31870.30734035]
 [ 9272.53265123 40184.9661095   1291.93881703 28988.81410135]
 [ 9679.05842748 42424.8828813   1180.0915659  26464.28634163]
 [10033.68359642 44380.60245546  1082.315529   24256.79660707]
 [10343.00087186 46087.34626275   996.92664686 22328.68

In [4]:

# plot results
plt.plot(t,y)
plt.xlabel('time')
plt.ylabel('y(t)')
plt.show()

NameError: name 'y' is not defined